[package]
name    = "blop-db"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "3"
members  = ["crates/blop-db-macros"]

[workspace.lints.clippy]
too_many_arguments = "allow"

[dependencies]
blop-db-macros = { path = "crates/blop-db-macros", version = "0.1.0" }

[lints.clippy]
too_many_arguments = "allow"
